# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VidCraft Pro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      #pod 'ffmpeg-kit-ios-tiny', '~> 4.4.2'
      #pod 'ffmpeg-kit-ios-full-gpl', '~> 6.0'
      pod 'PryntTrimmerView'
      pod 'Firebase/Core'             # Core Firebase SDK
      pod 'Firebase/Auth'             # Firebase Authentication

  # Pods for VidCraft Pro
end
